Numpy Tutorial
==============

Risorse
-------
https://numpy.org/devdocs/user/quickstart.html#prerequisites

https://numpy.org/devdocs/user/quickstart.html

In [4]:
import numpy as np


In [9]:
# monodimensional numpy array, called ndarray
ints = np.array([2,3,4])
print(ints)
print(ints.dtype)

[2 3 4]
int32


In [12]:
# monodimensional float ndarray
floats = np.array([1.2, 3.5, 5.1])
print(floats)
print(floats.dtype)

[1.2 3.5 5.1]
float64


In [24]:
# multidimensional array
points = np.array( [[0.0, 0.0, 0.0], [1.2, 0.0, 0.0], [0.0, 3.4, 0.0], [0.0, 0.0, 5.6]] )

# the whole array
print(points)

# number of axis, how many indexes are needed to identify a single value in the array
print(points.ndim) 

# shape, max count for each axis
print(points.shape)

# count numbers in the whole array
print(points.size)


[[0.  0.  0. ]
 [1.2 0.  0. ]
 [0.  3.4 0. ]
 [0.  0.  5.6]]
2
(4, 3)
12


In [37]:
# create an array full of zeros
zeros = np.zeros( (2, 3, 4) )
print(zeros)

# create an array full of ones
ones = np.ones( [2, 3, 4] )
print(ones)

# create an array with random values, called "empty" because no values are stored 
# there that differ from the ones in memory
empties = np.empty( [2, 2] )
print(empties)

# creates an array with this meaning:
# start value (included)
# end value (excluded)
# incremental step
arange = np.arange( -10, 90, 5 )
print(arange)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[4.22789158e-307 4.22789158e-307]
 [5.11782606e-307 8.34427737e-308]]
[-10  -5   0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75
  80  85  90]


In [6]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
c = np.array([[1.5,2,3], [4,5,6]])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])