Numpy tutorial
==============

https://numpy.org/devdocs/user/quickstart.html#prerequisites


In [3]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [6]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
c = np.array([[1.5,2,3], [4,5,6]])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])