NumPy
======

* supporto a grandi matrici 
* array multidimensionali 
* funzioni matematiche per operare su queste strutture dati.

Tutorial
-------

* https://numpy.org/devdocs/user/quickstart.html#prerequisites
* https://numpy.org/devdocs/user/quickstart.html
* https://www.tutorialspoint.com/numpy/index.htm

Cheatsheets
-------
* <https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf>


In [1]:
import numpy as np


In [7]:
# monodimensional numpy array, called ndarray
ints = np.array([2,3,4])
print(ints)
print(ints.dtype)

[2 3 4]
int32


In [8]:
# monodimensional float ndarray
floats = np.array([1.2, 3.5, 5.1])
print(floats)
print(floats.dtype)

[1.2 3.5 5.1]
float64


![Axis](https://miro.medium.com/max/2880/1*Ikn1J6siiiCSk4ivYUhdgw.png)

In [9]:
# bidimensional array
points = np.array( [[0.0, 0.0, 0.0], [1.2, 0.0, 0.0], [0.0, 3.4, 0.0], [0.0, 0.0, 5.6]] )

# the whole array
print("\npoints -----")
print(points)


# number of axis, how many indexes are needed to identify a single value in the array
print("\naxis -----")
print(points.ndim) 

# shape, max count for each axis
print("\nshape -----")
print(points.shape)

# count numbers in the whole array
print("\nsize -----")
print(points.size)



points -----
[[0.  0.  0. ]
 [1.2 0.  0. ]
 [0.  3.4 0. ]
 [0.  0.  5.6]]

axis -----
2

shape -----
(4, 3)

size -----
12


In [7]:
# create an array full of zeros, specifying the dimensions
zeros = np.zeros( (2, 3, 4) )
print("\n zeros -----")
print(zeros)

# create an array full of ones
ones = np.ones( [2, 3, 4] )
print("\n ones -----")
print(ones)

# create an array with random values, called "empty" because no values are stored 
# there that differ from the ones in memory
empties = np.empty( [2, 2] )
print("\n empties -----")
print(empties)

# creates an array with this meaning:
# start value (included)
# end value (excluded)
# incremental step
arange = np.arange( -10, 90, 5 )
print("\n arange -----")      
print(arange)

# creates an array containing values ranging from 20 to -20 with 81 items
lins = np.linspace( 20, -20, 81)
print("\n linspace -----")      
print(lins)

# return the interval between items too
lins = np.linspace( 10, 20, 40, retstep=True)
print("\n linspace 2 -----")      
print(lins)


 zeros -----
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

 ones -----
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

 empties -----
[[4.45042952e-307 2.55896735e-307]
 [9.79101081e-307 1.78020576e-306]]

 arange -----
[-10  -5   0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75
  80  85]

 linspace -----
[ 20.   19.5  19.   18.5  18.   17.5  17.   16.5  16.   15.5  15.   14.5
  14.   13.5  13.   12.5  12.   11.5  11.   10.5  10.    9.5   9.    8.5
   8.    7.5   7.    6.5   6.    5.5   5.    4.5   4.    3.5   3.    2.5
   2.    1.5   1.    0.5   0.   -0.5  -1.   -1.5  -2.   -2.5  -3.   -3.5
  -4.   -4.5  -5.   -5.5  -6.   -6.5  -7.   -7.5  -8.   -8.5  -9.   -9.5
 -10.  -10.5 -11.  -11.5 -12.  -12.5 -13.  -13.5 -14.  -14.5 -15.  -15.5
 -16.  -16.5 -17.  -17.5 -18.  -18.5 -19.  -19.5 -20. ]

 linspace 2 -----
(array([10.        , 10.25641026, 10.51282051, 10.76923077

In [13]:
# Reshape
tmp = np.arange(24)
print()
print(tmp)

tmp = tmp.reshape(2,12)
print()
print(tmp)

tmp = tmp.reshape(4,6)
print()
print(tmp)

tmp = tmp.reshape(3,2,4)
print()
print(tmp)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [29]:
# convert a Python array in a ndarray
pythonArr = [1,2,3] 
npArr = np.asarray(pythonArr)
print("\nnumpy array -----")
print(npArr)


numpy array -----
[1 2 3]


In [44]:
# fancy access
numbers = np.arange( 0, 20*2, 2 )
print(type(numbers))
print(numbers)

arr = numbers[:3]
print(type(arr))
print(arr)

arr = numbers[3:]
print(type(arr))
print(arr)

arr = numbers[3:5]
print(type(arr))
print(arr)

arr = numbers[-3:]
print(type(arr))
print(arr)


<class 'numpy.ndarray'>
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
<class 'numpy.ndarray'>
[0 2 4]
<class 'numpy.ndarray'>
[ 6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
<class 'numpy.ndarray'>
[6 8]
<class 'numpy.ndarray'>
[34 36 38]
<class 'numpy.ndarray'>
[]


In [12]:
arr1 = np.array([1,3,7])
arr2 = np.array([10,30,70])

print("\nsum arrays -----")
print( arr1 + arr2 )

print("\nmult arrays -----")
print( arr1 * arr2 )

print("\nsum elements -----")
print( np.sum( arr1 ) )

print("\nsqrt elements -----")
print( np.sqrt( arr1 ) )


sum arrays -----
[11 33 77]

mult arrays -----
[ 10  90 490]

sum elements -----
11

sqrt elements -----
[1.         1.73205081 2.64575131]


In [28]:
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.permutation.html
# try to run it multiple times!
np.random.permutation(12)

array([10,  6, 11,  0,  7,  2,  8,  5,  4,  1,  3,  9])